name: Continuous Integration
on: [pull_request]

jobs:
  lint:
    name: Lint
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: functions  
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Install
        run: yarn install --frozen-lockfile
        id: install
        working-directory:

      - name: Run prettier
        run: yarn run format:check

      - name: Run ESLint
        run: yarn run lint
        # Always run the linter, even if prettier failed
        if: ${{ steps.install.outcome == 'success' }}
